// Code generated by generate.go; DO NOT EDIT.
package gl

type V2 struct {
	BlendEquationSeparate    func(modeRGB BlendEquationModeEXT, modeAlpha BlendEquationModeEXT)                                          `libc:"glBlendEquationSeparate"`
	DrawBuffers              func(n int, bufs DrawBufferMode)                                                                            `libc:"glDrawBuffers"`
	StencilOpSeparate        func(face TriangleFace, sfail StencilOp, dpfail StencilOp, dppass StencilOp)                                `libc:"glStencilOpSeparate"`
	StencilFuncSeparate      func(face TriangleFace, func_ StencilFunction, ref int32, mask uint32)                                      `libc:"glStencilFuncSeparate"`
	StencilMaskSeparate      func(face TriangleFace, mask uint32)                                                                        `libc:"glStencilMaskSeparate"`
	AttachShader             func(program uint32, shader uint32)                                                                         `libc:"glAttachShader"`
	BindAttribLocation       func(program uint32, index uint32, name byte)                                                               `libc:"glBindAttribLocation"`
	CompileShader            func(shader uint32)                                                                                         `libc:"glCompileShader"`
	CreateProgram            func() uint32                                                                                               `libc:"glCreateProgram"`
	CreateShader             func(type_ ShaderType) uint32                                                                               `libc:"glCreateShader"`
	DeleteProgram            func(program uint32)                                                                                        `libc:"glDeleteProgram"`
	DeleteShader             func(shader uint32)                                                                                         `libc:"glDeleteShader"`
	DetachShader             func(program uint32, shader uint32)                                                                         `libc:"glDetachShader"`
	DisableVertexAttribArray func(index uint32)                                                                                          `libc:"glDisableVertexAttribArray"`
	EnableVertexAttribArray  func(index uint32)                                                                                          `libc:"glEnableVertexAttribArray"`
	GetActiveAttrib          func(program uint32, index uint32, bufSize int, length *int, size *int32, type_ *AttributeType, name *byte) `libc:"glGetActiveAttrib"`
	GetActiveUniform         func(program uint32, index uint32, bufSize int, length *int, size *int32, type_ *UniformType, name *byte)   `libc:"glGetActiveUniform"`
	GetAttachedShaders       func(program uint32, maxCount int, count *int, shaders *uint32)                                             `libc:"glGetAttachedShaders"`
	GetAttribLocation        func(program uint32, name byte) int32                                                                       `libc:"glGetAttribLocation"`
	GetProgramiv             func(program uint32, pname ProgramPropertyARB, params *int32)                                               `libc:"glGetProgramiv"`
	GetProgramInfoLog        func(program uint32, bufSize int, length *int, infoLog *byte)                                               `libc:"glGetProgramInfoLog"`
	GetShaderiv              func(shader uint32, pname ShaderParameterName, params *int32)                                               `libc:"glGetShaderiv"`
	GetShaderInfoLog         func(shader uint32, bufSize int, length *int, infoLog *byte)                                                `libc:"glGetShaderInfoLog"`
	GetShaderSource          func(shader uint32, bufSize int, length *int, source *byte)                                                 `libc:"glGetShaderSource"`
	GetUniformLocation       func(program uint32, name byte) int32                                                                       `libc:"glGetUniformLocation"`
	GetUniformfv             func(program uint32, location int32, params *float32)                                                       `libc:"glGetUniformfv"`
	GetUniformiv             func(program uint32, location int32, params *int32)                                                         `libc:"glGetUniformiv"`
	GetVertexAttribdv        func(index uint32, pname VertexAttribPropertyARB, params *float64)                                          `libc:"glGetVertexAttribdv"`
	GetVertexAttribfv        func(index uint32, pname VertexAttribPropertyARB, params *float32)                                          `libc:"glGetVertexAttribfv"`
	GetVertexAttribiv        func(index uint32, pname VertexAttribPropertyARB, params *int32)                                            `libc:"glGetVertexAttribiv"`
	GetVertexAttribPointerv  func(index uint32, pname VertexAttribPointerPropertyARB, pointer *Pointer)                                  `libc:"glGetVertexAttribPointerv"`
	IsProgram                func(program uint32) bool                                                                                   `libc:"glIsProgram"`
	IsShader                 func(shader uint32) bool                                                                                    `libc:"glIsShader"`
	LinkProgram              func(program uint32)                                                                                        `libc:"glLinkProgram"`
	ShaderSource             func(shader uint32, count int, string byte, length int32)                                                   `libc:"glShaderSource"`
	UseProgram               func(program uint32)                                                                                        `libc:"glUseProgram"`
	Uniform1f                func(location int32, v0 float32)                                                                            `libc:"glUniform1f"`
	Uniform2f                func(location int32, v0 float32, v1 float32)                                                                `libc:"glUniform2f"`
	Uniform3f                func(location int32, v0 float32, v1 float32, v2 float32)                                                    `libc:"glUniform3f"`
	Uniform4f                func(location int32, v0 float32, v1 float32, v2 float32, v3 float32)                                        `libc:"glUniform4f"`
	Uniform1i                func(location int32, v0 int32)                                                                              `libc:"glUniform1i"`
	Uniform2i                func(location int32, v0 int32, v1 int32)                                                                    `libc:"glUniform2i"`
	Uniform3i                func(location int32, v0 int32, v1 int32, v2 int32)                                                          `libc:"glUniform3i"`
	Uniform4i                func(location int32, v0 int32, v1 int32, v2 int32, v3 int32)                                                `libc:"glUniform4i"`
	Uniform1fv               func(location int32, count int, value float32)                                                              `libc:"glUniform1fv"`
	Uniform2fv               func(location int32, count int, value float32)                                                              `libc:"glUniform2fv"`
	Uniform3fv               func(location int32, count int, value float32)                                                              `libc:"glUniform3fv"`
	Uniform4fv               func(location int32, count int, value float32)                                                              `libc:"glUniform4fv"`
	Uniform1iv               func(location int32, count int, value int32)                                                                `libc:"glUniform1iv"`
	Uniform2iv               func(location int32, count int, value int32)                                                                `libc:"glUniform2iv"`
	Uniform3iv               func(location int32, count int, value int32)                                                                `libc:"glUniform3iv"`
	Uniform4iv               func(location int32, count int, value int32)                                                                `libc:"glUniform4iv"`
	UniformMatrix2fv         func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix2fv"`
	UniformMatrix3fv         func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix3fv"`
	UniformMatrix4fv         func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix4fv"`
	ValidateProgram          func(program uint32)                                                                                        `libc:"glValidateProgram"`
	VertexAttrib1d           func(index uint32, x float64)                                                                               `libc:"glVertexAttrib1d"`
	VertexAttrib1dv          func(index uint32, v float64)                                                                               `libc:"glVertexAttrib1dv"`
	VertexAttrib1f           func(index uint32, x float32)                                                                               `libc:"glVertexAttrib1f"`
	VertexAttrib1fv          func(index uint32, v float32)                                                                               `libc:"glVertexAttrib1fv"`
	VertexAttrib1s           func(index uint32, x int16)                                                                                 `libc:"glVertexAttrib1s"`
	VertexAttrib1sv          func(index uint32, v int16)                                                                                 `libc:"glVertexAttrib1sv"`
	VertexAttrib2d           func(index uint32, x float64, y float64)                                                                    `libc:"glVertexAttrib2d"`
	VertexAttrib2dv          func(index uint32, v float64)                                                                               `libc:"glVertexAttrib2dv"`
	VertexAttrib2f           func(index uint32, x float32, y float32)                                                                    `libc:"glVertexAttrib2f"`
	VertexAttrib2fv          func(index uint32, v float32)                                                                               `libc:"glVertexAttrib2fv"`
	VertexAttrib2s           func(index uint32, x int16, y int16)                                                                        `libc:"glVertexAttrib2s"`
	VertexAttrib2sv          func(index uint32, v int16)                                                                                 `libc:"glVertexAttrib2sv"`
	VertexAttrib3d           func(index uint32, x float64, y float64, z float64)                                                         `libc:"glVertexAttrib3d"`
	VertexAttrib3dv          func(index uint32, v float64)                                                                               `libc:"glVertexAttrib3dv"`
	VertexAttrib3f           func(index uint32, x float32, y float32, z float32)                                                         `libc:"glVertexAttrib3f"`
	VertexAttrib3fv          func(index uint32, v float32)                                                                               `libc:"glVertexAttrib3fv"`
	VertexAttrib3s           func(index uint32, x int16, y int16, z int16)                                                               `libc:"glVertexAttrib3s"`
	VertexAttrib3sv          func(index uint32, v int16)                                                                                 `libc:"glVertexAttrib3sv"`
	VertexAttrib4Nbv         func(index uint32, v int8)                                                                                  `libc:"glVertexAttrib4Nbv"`
	VertexAttrib4Niv         func(index uint32, v int32)                                                                                 `libc:"glVertexAttrib4Niv"`
	VertexAttrib4Nsv         func(index uint32, v int16)                                                                                 `libc:"glVertexAttrib4Nsv"`
	VertexAttrib4Nub         func(index uint32, x uint8, y uint8, z uint8, w uint8)                                                      `libc:"glVertexAttrib4Nub"`
	VertexAttrib4Nubv        func(index uint32, v uint8)                                                                                 `libc:"glVertexAttrib4Nubv"`
	VertexAttrib4Nuiv        func(index uint32, v uint32)                                                                                `libc:"glVertexAttrib4Nuiv"`
	VertexAttrib4Nusv        func(index uint32, v uint16)                                                                                `libc:"glVertexAttrib4Nusv"`
	VertexAttrib4bv          func(index uint32, v int8)                                                                                  `libc:"glVertexAttrib4bv"`
	VertexAttrib4d           func(index uint32, x float64, y float64, z float64, w float64)                                              `libc:"glVertexAttrib4d"`
	VertexAttrib4dv          func(index uint32, v float64)                                                                               `libc:"glVertexAttrib4dv"`
	VertexAttrib4f           func(index uint32, x float32, y float32, z float32, w float32)                                              `libc:"glVertexAttrib4f"`
	VertexAttrib4fv          func(index uint32, v float32)                                                                               `libc:"glVertexAttrib4fv"`
	VertexAttrib4iv          func(index uint32, v int32)                                                                                 `libc:"glVertexAttrib4iv"`
	VertexAttrib4s           func(index uint32, x int16, y int16, z int16, w int16)                                                      `libc:"glVertexAttrib4s"`
	VertexAttrib4sv          func(index uint32, v int16)                                                                                 `libc:"glVertexAttrib4sv"`
	VertexAttrib4ubv         func(index uint32, v uint8)                                                                                 `libc:"glVertexAttrib4ubv"`
	VertexAttrib4uiv         func(index uint32, v uint32)                                                                                `libc:"glVertexAttrib4uiv"`
	VertexAttrib4usv         func(index uint32, v uint16)                                                                                `libc:"glVertexAttrib4usv"`
	VertexAttribPointer      func(index uint32, size int32, type_ VertexAttribPointerType, normalized bool, stride int, pointer Pointer) `libc:"glVertexAttribPointer"`
	UniformMatrix2x3fv       func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix2x3fv"`
	UniformMatrix3x2fv       func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix3x2fv"`
	UniformMatrix2x4fv       func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix2x4fv"`
	UniformMatrix4x2fv       func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix4x2fv"`
	UniformMatrix3x4fv       func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix3x4fv"`
	UniformMatrix4x3fv       func(location int32, count int, transpose bool, value float32)                                              `libc:"glUniformMatrix4x3fv"`
}
