// Code generated by gen/gen.c; DO NOT EDIT.

package cgo

const (
	c_CHAR_BIT               = 8
	c_MB_LEN_MAX             = 16
	c_CHAR_MIN               = -128
	c_CHAR_MAX               = 127
	c_SCHAR_MIN              = -128
	c_SHRT_MIN               = -32768
	c_INT_MIN                = -2147483648
	c_LONG_MIN               = -9223372036854775808
	c_LLONG_MIN              = -9223372036854775808
	c_SCHAR_MAX              = 127
	c_SHRT_MAX               = 32767
	c_INT_MAX                = 2147483647
	c_LONG_MAX               = 9223372036854775807
	c_LLONG_MAX              = 9223372036854775807
	c_UCHAR_MAX              = 255
	c_USHRT_MAX              = 65535
	c_UINT_MAX               = 4294967295
	c_ULONG_MAX              = 18446744073709551615
	c_ULLONG_MAX             = 18446744073709551615
	c_PTRDIFF_MIN            = -9223372036854775808
	c_PTRDIFF_MAX            = 9223372036854775807
	c_SIZE_MAX               = 18446744073709551615
	c_WINT_MIN               = 0
	c_WINT_MAX               = -1
	c_WCHAR_MIN              = -2147483648
	c_WCHAR_MAX              = 2147483647
	c_INT8_MIN               = -128
	c_INT16_MIN              = -32768
	c_INT32_MIN              = -2147483648
	c_INT64_MIN              = -9223372036854775808
	c_INT8_MAX               = 127
	c_INT16_MAX              = 32767
	c_INT32_MAX              = 2147483647
	c_INT64_MAX              = 9223372036854775807
	c_UINT8_MAX              = 255
	c_UINT16_MAX             = 65535
	c_UINT32_MAX             = 4294967295
	c_UINT64_MAX             = 18446744073709551615
	c_INT_FAST8_MIN          = -128
	c_INT_FAST16_MIN         = -9223372036854775808
	c_INT_FAST32_MIN         = -9223372036854775808
	c_INT_FAST64_MIN         = -9223372036854775808
	c_INT_FAST8_MAX          = 127
	c_INT_FAST16_MAX         = 9223372036854775807
	c_INT_FAST32_MAX         = 9223372036854775807
	c_INT_FAST64_MAX         = 9223372036854775807
	c_UINT_FAST8_MAX         = 255
	c_UINT_FAST16_MAX        = 18446744073709551615
	c_UINT_FAST32_MAX        = 18446744073709551615
	c_UINT_FAST64_MAX        = 18446744073709551615
	c_INT_LEAST8_MIN         = -128
	c_INT_LEAST16_MIN        = -32768
	c_INT_LEAST32_MIN        = -2147483648
	c_INT_LEAST64_MIN        = -9223372036854775808
	c_INT_LEAST8_MAX         = 127
	c_INT_LEAST16_MAX        = 32767
	c_INT_LEAST32_MAX        = 2147483647
	c_INT_LEAST64_MAX        = 9223372036854775807
	c_UINT_LEAST8_MAX        = 255
	c_UINT_LEAST16_MAX       = 65535
	c_UINT_LEAST32_MAX       = 4294967295
	c_UINT_LEAST64_MAX       = 18446744073709551615
	c_INTMAX_MIN             = -9223372036854775808
	c_INTMAX_MAX             = 9223372036854775807
	c_UINTMAX_MAX            = 18446744073709551615
	c_INTPTR_MIN             = -9223372036854775808
	c_INTPTR_MAX             = 9223372036854775807
	c_UINTPTR_MAX            = 18446744073709551615
	c_SIG_ATOMIC_MIN         = -2147483648
	c_SIG_ATOMIC_MAX         = 2147483647
	c_FLT_RADIX              = 2
	c_DECIMAL_DIG            = 21
	c_FLT_DECIMAL_DIG        = 9
	c_DBL_DECIMAL_DIG        = 17
	c_LDBL_DECIMAL_DIG       = 21
	c_FLT_MIN                = 1.175494e-38
	c_DBL_MIN                = 2.225074e-308
	c_LDBL_MIN               = 3.362103e-4932
	c_FLT_TRUE_MIN           = 1.401298e-45
	c_DBL_TRUE_MIN           = 4.940656e-324
	c_LDBL_TRUE_MIN          = 3.645200e-4951
	c_FLT_MAX                = 3.402823e+38
	c_DBL_MAX                = 1.797693e+308
	c_LDBL_MAX               = 1.189731e+4932
	c_FLT_EPSILON            = 1.192093e-07
	c_DBL_EPSILON            = 2.220446e-16
	c_LDBL_EPSILON           = 1.084202e-19
	c_FLT_DIG                = 6
	c_DBL_DIG                = 15
	c_LDBL_DIG               = 18
	c_FLT_MANT_DIG           = 24
	c_DBL_MANT_DIG           = 53
	c_LDBL_MANT_DIG          = 64
	c_FLT_MIN_EXP            = -125
	c_DBL_MIN_EXP            = -1021
	c_LDBL_MIN_EXP           = -16381
	c_FLT_MIN_10_EXP         = -37
	c_DBL_MIN_10_EXP         = -307
	c_LDBL_MIN_10_EXP        = -4931
	c_FLT_MAX_EXP            = 128
	c_DBL_MAX_EXP            = 1024
	c_LDBL_MAX_EXP           = 16384
	c_FLT_MAX_10_EXP         = 38
	c_DBL_MAX_10_EXP         = 308
	c_LDBL_MAX_10_EXP        = 4932
	c_FLT_ROUNDS             = 1
	c_FLT_EVAL_METHOD        = 0
	c_FLT_HAS_SUBNORM        = 1
	c_DBL_HAS_SUBNORM        = 1
	c_LDBL_HAS_SUBNORM       = 1
	c_EDOM                   = 33
	c_ERANGE                 = 34
	c_EILSEQ                 = 84
	c_FE_DFL_ENV             = 0
	c_FE_DIVBYZERO           = 4
	c_FE_INEXACT             = 32
	c_FE_INVALID             = 1
	c_FE_OVERFLOW            = 8
	c_FE_UNDERFLOW           = 16
	c_FE_ALL_EXCEPT          = 61
	c_fegetround             = 0
	c_FE_DOWNWARD            = 1024
	c_FE_TONEAREST           = 0
	c_FE_TOWARDZERO          = 3072
	c_FE_UPWARD              = 2048
	c_FP_NORMAL              = 4
	c_FP_SUBNORMAL           = 3
	c_FP_ZERO                = 2
	c_FP_INFINITE            = 1
	c_FP_NAN                 = 0
	c_SIGTERM                = 15
	c_SIGSEGV                = 11
	c_SIGINT                 = 2
	c_SIGILL                 = 4
	c_SIGABRT                = 6
	c_SIGFPE                 = 8
	c_LC_ALL                 = 6
	c_LC_COLLATE             = 3
	c_LC_CTYPE               = 0
	c_LC_MONETARY            = 4
	c_LC_NUMERIC             = 1
	c_LC_TIME                = 2
	c_MATH_ERRNO             = 1
	c_MATH_ERREXCEPT         = 2
	c_math_errhandling       = 3
	c_EXIT_SUCCESS           = 0
	c_EXIT_FAILURE           = 1
	c_true                   = 1
	c_false                  = 0
	c_ATOMIC_BOOL_LOCK_FREE  = 2
	c_ATOMIC_CHAR_LOCK_FREE  = 2
	c_ATOMIC_CHAR16_T_LOCK_FREE  = 2
	c_ATOMIC_CHAR32_T_LOCK_FREE  = 2
	c_ATOMIC_WCHAR_T_LOCK_FREE  = 2
	c_ATOMIC_SHORT_LOCK_FREE  = 2
	c_ATOMIC_INT_LOCK_FREE  = 2
	c_ATOMIC_LONG_LOCK_FREE  = 2
	c_ATOMIC_LLONG_LOCK_FREE  = 2
	c_ATOMIC_POINTER_LOCK_FREE  = 2
	c_EOF                   = -1
	c_FOPEN_MAX             = 16
	c_FILENAME_MAX          = 4096
	c_L_tmpnam              = 20
	c_TMP_MAX               = 238328
	c__IOFBF                 = 0
	c__IOLBF                 = 1
	c__IONBF                 = 2
	c_BUFSIZ                = 8192
	c_SEEK_SET              = 0
	c_SEEK_CUR              = 1
	c_SEEK_END              = 2
	c_CLOCKS_PER_SEC        = 1000000
)

type (
	c_char                int8
	c_signed_char         int8
	c_unsigned_char       uint8
	c_short               int16
	c_unsigned_short      uint16
	c_int                 int32
	c_unsigned_int        uint32
	c_long                int64
	c_unsigned_long       uint64
	c_longlong            int64
	c_unsigned_longlong   uint64
	c_float               float32
	c_double              float64
	c_long_double         float64
	c_float_t             float32
	c_double_t            float64
	c_int8_t              int8
	c_int16_t             int16
	c_int32_t             int32
	c_int64_t             int64
	c_uint8_t             uint8
	c_uint16_t            uint16
	c_uint32_t            uint32
	c_uint64_t            uint64
	c_char16_t            int16
	c_char32_t            int32
	c_wchar_t             int32
	c_wint_t              int32
	c_size_t               uint64
	c_time_t               int64
	c_clock_t              int64
	c_bool                 uint8
	c_uintptr_t           uint64
	c_ptrdiff_t           int64
	c_intptr_t               int64
	c_max_align_t         [32]byte
	c_sig_atomic_t        int32
	c_intmax_t                int64
	c_uintmax_t               uint64
	c_int_fast8_t             int8
	c_int_fast16_t            int64
	c_int_fast32_t            int64
	c_int_fast64_t            int64
	c_uint_fast8_t            uint8
	c_uint_fast16_t           uint64
	c_uint_fast32_t           uint64
	c_uint_fast64_t           uint64
	c_int_least8_t             int8
	c_int_least16_t            int16
	c_int_least32_t            int32
	c_int_least64_t            int64
	c_uint_least8_t            uint8
	c_uint_least16_t           uint16
	c_uint_least32_t           uint32
	c_uint_least64_t           uint64
)

type c_fenv_t [32]byte

type c_jmp_buf [200]byte

type c_FILE [216]byte

type c_fpos_t [16]byte

type c_va_list [24]byte

type c_mbstate_t [8]byte

