// this should import dyncall C files
#include "dynload/dynload.c"
#include "dyncall/dyncall_aggregate.c"
#include "dyncall/dyncall_args.c"
#include "dyncall/dyncall_callf.c"
#include "dyncall/dyncall_callvm.c"
#include "dyncall/dyncall_api.c"
#include "dyncall/dyncall_thunk.c"
#include "dyncall/dyncall_vector.c"
#include "dyncall/dyncall_callvm_base.c"
#include "dyncall/dyncall_call.S"